name: Question (English)
description: I have a question about this EFI
title: "[Question] Enter a title"
labels: ["question", "english"]
assignees:
  - AurelienAudero
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this form
  - type: textarea
    id: question
    attributes:
      label: What is your question ?
      description: A clear and concise description of your question
      value: "Type here"
    validations:
      required: true
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else ?
      description: |
        Links ? References ? Anything that will give us more context about your question
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in
  - type: checkboxes
    id: checklist
    attributes:
      label: I'm checking my form
      description: Check through this checklist that the form is correct and that it has been completed correctly.
      options:
        - label: My question is not about a bug or issue I have using this EFI (if so, I use the form named "Bug/Issue Report")
          required: true
        - label: I have specified a title related to my problem
          required: true
        - label: My title starts with "[Question]" (without the quotes)
          required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this question, you agree to follow our [Code of Conduct](https://github.com/AurelienAudero/Intel-i5-7400-Hackintosh-EFI/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
